-- =============================================================================
-- SoilNSoul Travels — PostgreSQL Data Seed / Backup
-- Generated: 2026-10-01T06:59:47.558Z
-- =============================================================================

-- Data for admins (1 rows)
INSERT INTO admins (id, name, email, password_hash, role, avatar, last_login, created_at, updated_at) VALUES ('69a6da0890bf42dff21acec3', 'Soil n Soul Admin', 'admin@soilnsoul.in', '$2a$12$6JfVDwIB9IfGzUZWUJekgODFzN.CYGJCl46m.v7Fxmbq6QTkyzFv2', 'admin', '', '"2026-09-30T14:56:36.341Z"'::jsonb, '"2026-03-03T12:54:32.214Z"'::jsonb, '"2026-09-30T14:56:36.341Z"'::jsonb) ON CONFLICT (id) DO NOTHING;

-- Data for blogs (5 rows)
INSERT INTO blogs (id, title, slug, excerpt, content, banner_image, category, status, tags, seo_title, seo_description, seo_keywords, published, created_at, updated_at) VALUES ('editorial-aarti-1', 'The Magic of Ganga Aarti: Faith, Fire, and the Sacred River', 'the-magic-of-ganga-aarti', 'Faith, fire, and an experience that stays with you forever as dusk falls over Dashashwamedh Ghat.', '<p class="lead">Every evening at twilight, as the sun dips beneath the eastern sands of the Ganges, the ancient steps of Dashashwamedh Ghat transform into a sacred theater of devotion that has continued uninterrupted for centuries.</p>
<h2>The Geometry of Devotion</h2>
<p>Young priests adorned in saffron dhotis ascend elevated wooden platforms. With synchronized grace, they lift towering multi-tiered brass lamps carrying burning camphor. The rhythmic resonance of bronze bells, conch shells, and Vedic chants fills the cool evening air, echoing across the gentle current of the river.</p>
<blockquote>"The river does not simply reflect the light of the lamps; it absorbs the prayers of thousands who have gathered on wooden boats to witness the eternal rhythm of Kashi."</blockquote>
<h2>Witnessing Aarti from the Water</h2>
<p>While thousands gather on the steps, the most intimate and contemplative way to experience the Ganga Aarti is from a private wooden boat resting gently upon the current. As the lamps burn bright, the waters are covered in thousands of floating leaf boats carrying marigolds and flickers of flame, drifting into the velvet night.</p>
<h2>Practical Guide for the Conscious Traveler</h2>
<ul>
  <li><strong>Optimal Timing:</strong> Arrive by boat at least 35 minutes before sunset to secure a peaceful vantage point.</li>
  <li><strong>Summer vs. Winter:</strong> In winter, Aarti begins around 6:00 PM; during the long summer twilights, it shifts closer to 7:00 PM.</li>
  <li><strong>Cultural Etiquette:</strong> Maintain silence during the sacred aarti hymns, dress modestly covering shoulders and knees, and respectfully offer your diya with both hands to the river.</li>
</ul>
<p>At SoilNSoul Travels, our private twilight boat journeys include a dedicated local cultural guide who explains the esoteric meaning behind each step of the ceremony, from the peacock-feather fans to the sacred fire rituals honoring Mother Ganga.</p>', '/images/journal-ref/featured_ganga_aarti_clean.jpg', 'Spirituality', 'published', '["ganga aarti","varanasi","dashashwamedh ghat","spirituality","kashi"]'::jsonb, 'The Magic of Ganga Aarti in Varanasi | SoilNSoul Travels', 'Experience the mystical Ganga Aarti ceremony at Dashashwamedh Ghat in Varanasi. Ancient chants, brass lamps, and river reflections with SoilNSoul Travels.', '["Ganga Aarti Varanasi","Dashashwamedh Ghat Aarti","Varanasi spiritual ceremony","Ganga Aarti timing"]'::jsonb, true, '"2026-10-01T06:58:58.704Z"'::jsonb, '"2026-10-01T06:58:58.704Z"'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO blogs (id, title, slug, excerpt, content, banner_image, category, status, tags, seo_title, seo_description, seo_keywords, published, created_at, updated_at) VALUES ('editorial-card-1', 'A Perfect Day in Varanasi: A Soulful Guide Beyond the Usual', 'a-perfect-day-in-varanasi', 'A soulful guide to experiencing Kashi beyond the usual, from silent sunrise oars to hidden haveli courtyards.', '<p class="lead">Varanasi is not a city that yields its secrets to hurried checklists. To understand Kashi, one must surrender to its ancient rhythm—a slow waking at dawn, a sensory labyrinth of narrow galis at midday, and a quiet stillness beside the sacred river at night.</p>
<h2>Dawn: The Awakening of the Ghats (5:30 AM – 8:00 AM)</h2>
<p>Begin before sunrise at Assi Ghat. Step aboard a handcrafted wooden oar boat as the morning mist hovers over the holy Ganga. As the first amber rays touch the sandstone spires of the ancient ghats, witness pilgrims offering morning Surya Arghya. The silence is punctuated only by the rhythmic dip of wooden oars and morning temple bells.</p>
<h2>Morning: The Alleys and Breakfast Traditions (8:30 AM – 11:00 AM)</h2>
<p>Disembark near Manikarnika and enter the labyrinthine galis of the old city. Enjoy hot, crisp kachoris paired with spicy potato curry and freshly fried jalebis served on dried leaf plates, followed by rich Banarasi tea in a traditional terracotta kulhad.</p>
<blockquote>"Walking the ancient alleys of Kashi is like traveling backward through five thousand years of continuous human faith and architectural heritage."</blockquote>
<h2>Afternoon: Heritage, Silk Weavers & Sarnath (12:00 PM – 4:30 PM)</h2>
<p>Escape the midday bustle by visiting the ancient Buddhist sanctuary of Sarnath, where Lord Buddha gave his first sermon. Return to Varanasi to explore the traditional Julaha weaver neighborhoods, witnessing the master craftsmen who spend weeks hand-weaving pure zari silk sarees on antique wooden jacquard looms.</p>
<h2>Dusk: The Sacred Aarti and Night Contemplation (5:30 PM – 9:00 PM)</h2>
<p>Conclude your day with a private boat charter for the Dashashwamedh Ghat Ganga Aarti, followed by dinner overlooking the illuminated river facade from a heritage terrace.</p>', '/images/journal-ref/card1_sunrise_hd.jpg', 'Travel Guide', 'published', '["varanasi itinerary","sunrise boat ride","kashi guide","hidden banaras"]'::jsonb, 'A Perfect Day in Varanasi | SoilNSoul Travels', 'How to spend a perfect day in Varanasi. An authentic 24-hour itinerary through sacred dawn boat rides, street food, ancient alleys, and silk quarters.', '["one day in Varanasi","Varanasi travel itinerary","best things to do in Varanasi"]'::jsonb, true, '"2026-10-01T06:58:58.765Z"'::jsonb, '"2026-10-01T06:58:58.765Z"'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO blogs (id, title, slug, excerpt, content, banner_image, category, status, tags, seo_title, seo_description, seo_keywords, published, created_at, updated_at) VALUES ('editorial-card-2', 'The Artisans of Banaras: Stories of the Master Silk Weavers', 'the-artisans-of-banaras', 'Stories of the weavers keeping centuries-old traditions alive through pure silk, intricate zari, and heritage pit looms.', '<p class="lead">Behind the bustling market stalls of Chowk and Vishwanath Gali lies the rhythmic cadence of the pit looms—a steady, hypnotic clack that has echoed through the Muslim and Hindu neighborhoods of Varanasi for more than five centuries.</p>
<h2>The Heritage of the Julahas</h2>
<p>In quarters like Madanpura, Peelo Kothi, and Lallapura, generations of families have dedicated their lives to Banarasi handloom weaving. Master craftsmen, known locally as <em>Karigars</em>, work in ground-floor workshops using wooden looms that sink directly into the earthen floor.</p>
<h2>The Alchemy of Pure Zari and Silk</h2>
<p>Authentic Banarasi silk is distinguished by its intricate brocade designs woven with gold and silver threads known as zari. A single bespoke bridal saree featuring classical motifs—such as the <em>shikargah</em> (hunting scene), <em>jangla</em> (floral scroll), or <em>boota</em>—can take up to three months of painstaking manual labor.</p>
<blockquote>"Every thread is not just silk; it is an inheritance passed from grandfather to grandson, carrying the soul of Varanasi in every warp and weft."</blockquote>
<h2>Supporting Living Heritage</h2>
<p>With the rise of industrial powerlooms, genuine handloom weaving faces immense challenges. SoilNSoul Travels bridges the gap by bringing discerning travelers directly into the homes of master weaver families—allowing visitors to appreciate the craftsmanship, hear firsthand stories, and acquire authentic textiles directly from the makers without middlemen.</p>', '/SnS/banarasi-silk-detail.webp', 'Crafts & Culture', 'published', '["banarasi silk","handloom","artisans","kashi culture"]'::jsonb, 'The Artisans of Banaras: Master Silk Weavers | SoilNSoul Travels', 'Meet the master Banarasi silk weavers of Varanasi. Learn about handloom traditions, pure zari craft, and the artisan families preserving century-old textiles.', '["Banarasi silk saree weavers","Varanasi handloom","Banaras craft heritage"]'::jsonb, true, '"2026-10-01T06:58:58.768Z"'::jsonb, '"2026-10-01T06:58:58.768Z"'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO blogs (id, title, slug, excerpt, content, banner_image, category, status, tags, seo_title, seo_description, seo_keywords, published, created_at, updated_at) VALUES ('editorial-card-3', 'Temples That Tell Stories: Sacred Architecture and Hidden Shrines', 'temples-that-tell-stories', 'Sacred spaces, deeper meanings, and timeless legends etched into stone along the ancient ghats of Varanasi.', '<p class="lead">It is often said that every stone in Kashi holds a deity, and every turn in its ancient alleys leads to a sanctuary. Beyond the prominent spires lies a city where every corner, alley, and stone carries thousands of years of devotion.</p>
<h2>Kashi Vishwanath: The Golden Axis</h2>
<p>Dedicated to Lord Shiva as the Lord of the Universe (Vishwanath), this Jyotirlinga shrine is the spiritual epicenter of Hinduism. Rebuilt through periods of intense historical turmoil, its spire plated in genuine gold stands as an enduring symbol of resilience, faith, and cosmic light.</p>
<h2>The Red Spires of Kedareswar</h2>
<p>Perched high above Kedar Ghat, the Kedareswar Temple is older in legend than Vishwanath itself. Its distinctive red-and-white striped facade recalls traditional South Indian temple aesthetics, illustrating how Varanasi has gathered pilgrims from every corner of the subcontinent for thousands of years.</p>
<blockquote>"In the quiet courtyards of Kashi''s lesser-known temples, time slows down. The stone steps, worn smooth by centuries of bare feet, radiate a stillness found nowhere else."</blockquote>
<h2>The Sunken Wonder of Ratneshwar Mahadev</h2>
<p>Leaning precariously towards the river at Manikarnika Ghat, the 9-degree tilt of the Ratneshwar temple surpasses even the Leaning Tower of Pisa. Submerged in Ganga''s waters for several months of the monsoon each year, its exquisite stone carvings emerge intact season after season.</p>
<p>Our private Temple Circuit journeys are led by local scholars who reveal not only the architectural majesty of these sacred structures, but the living philosophical traditions practiced within them today.</p>', '/images/journal-ref/card3_temples_hd.jpg', 'Spirituality', 'published', '["temples","kashi vishwanath","architecture","sacred shrines"]'::jsonb, 'Temples That Tell Stories in Varanasi | SoilNSoul Travels', 'Discover the hidden temples and ancient architecture of Varanasi. From Kashi Vishwanath to Kedareswar and neighborhood shrines with SoilNSoul Travels.', '["Varanasi temples","Kashi Vishwanath","hidden shrines Varanasi"]'::jsonb, true, '"2026-10-01T06:58:58.771Z"'::jsonb, '"2026-10-01T06:58:58.771Z"'::jsonb) ON CONFLICT (id) DO NOTHING;
INSERT INTO blogs (id, title, slug, excerpt, content, banner_image, category, status, tags, seo_title, seo_description, seo_keywords, published, created_at, updated_at) VALUES ('editorial-card-4', 'A Woman’s Journey Through Kashi: Safety, Stories, and Exploring Solo', 'a-womans-journey-through-kashi', 'Safety, stories, and the joy of exploring solo in Varanasi with confidence, intuition, and trusted local guidance.', '<p class="lead">Varanasi often evokes images of intensity—crowds, sounds, and vibrant energy. Yet for female solo travelers seeking genuine depth, Kashi offers a remarkably nurturing, soulful, and spiritually transformative sanctuary when approached with the right awareness and local support.</p>
<h2>Intuition, Respect, and Confidence</h2>
<p>The spirit of Varanasi is deeply respectful of travelers who honor its sacred traditions. Walking the river ghats early in the morning is one of the most serene experiences imaginable—pilgrims are immersed in prayer, boatmen prepare their craft, and the morning sun bathes the ancient sandstone in warm gold.</p>
<h2>Practical Tips for Solo Women Travelers</h2>
<ul>
  <li><strong>Choosing Accommodations:</strong> Opt for verified heritage havelis or boutique riverside properties with 24/7 staff, gated entrances, and direct ghat access.</li>
  <li><strong>Cultural Dressing:</strong> Wearing loose, breathable linen kurtas or long dresses covering the shoulders and knees ensures complete ease of movement and deep respect in religious quarters.</li>
  <li><strong>Evening Movement:</strong> While main ghats like Assi and Dashashwamedh remain lively until late evening, navigating unlit back alleys after dark is best done with a trusted local escort.</li>
</ul>
<blockquote>"Varanasi taught me that stillness is not the absence of sound, but the presence of peace within oneself amidst the sacred river''s current."</blockquote>
<h2>The SoilNSoul Travels Local Concierge</h2>
<p>To provide peace of mind, SoilNSoul Travels pairs solo women travelers with verified, culturally sensitive local concierges. Whether navigating crowded markets, coordinating private dawn boat rides, or arranging vetted airport transfers, we ensure your journey through Varanasi is safe, enriching, and unforgettable.</p>', '/images/journal-ref/card4_solowoman_hd.jpg', 'Solo Women Travel', 'published', '["solo female travel","safety in varanasi","kashi travel tips"]'::jsonb, 'A Woman’s Journey Through Kashi | Solo Female Travel Varanasi', 'A practical, empowering guide for women traveling solo in Varanasi. Safety advice, cultural etiquette, boutique stays, and curated private concierge support.', '["solo female travel Varanasi","women traveling Varanasi","Varanasi safety tips"]'::jsonb, true, '"2026-10-01T06:58:58.773Z"'::jsonb, '"2026-10-01T06:58:58.773Z"'::jsonb) ON CONFLICT (id) DO NOTHING;

-- Data for hotels (1 rows)
INSERT INTO hotels (id, name, description, image, whatsapp_message, created_at, updated_at) VALUES ('69c62d76c9013b5cd64d70c8', 'Saraswati hotel', 'sdfghjkl;''', 'https://www.orchidhotel.com/static/website/img/hotels/panchgani/homepage_slider/homepage_slider.webp', 'hi i need this hotel saraswati', '"2026-03-27T07:10:46.927Z"'::jsonb, '"2026-03-27T07:10:46.927Z"'::jsonb) ON CONFLICT (id) DO NOTHING;

-- Data for inquiries (1 rows)
INSERT INTO inquiries (id, name, phone, email, service, dates, guests, origin, interests, message, status, source, notes, metadata, created_at, updated_at) VALUES ('6abcebfba7892a07c33a5652', 'Aditi Sharma', '+91 9876543210', 'aditi@example.com', 'A custom Kashi trip', '2026-10-15', '2 to 3', 'Mumbai', '', 'Sunrise boat tour requested', 'resolved', 'journey_enquiry', '', '{}'::jsonb, '"2026-09-30T11:01:15.533Z"'::jsonb, '"2026-09-30T14:58:25.870Z"'::jsonb) ON CONFLICT (id) DO NOTHING;

